const express = require('express')
const router = express.Router()
const { signup, signin } = require('../controllers/auth')
const { getBooks , getBook } = require('../controllers/books')
const { moreBooks } = require('../controllers/moreBooks')
router.post('/signup', signup)
router.post('/signin', signin)
router.get('/books', getBooks)
router.get('/books/:id', getBook)
router.post('/moreBooks' , moreBooks)
module.exports = router
